### PR TITLE
SLING-9157 ResourceUtil minor fixes

### PR DESCRIPTION
**Pull request by npeltier**
- making that utility class final,
- adding private constructor to prevent implicit constructor to be used

### CODE REVIEW

**Comment by raducotescu** [comment]
This introduces a backwards incompatible change which is not needed.

**Comment by npeltier** [comment]
@raducotescu this change would be backward incompatible with super anti pattern usage, wouldn't it? In such case can we go on speaking about backward incompatible?

**Comment by raducotescu** [comment]
> @raducotescu this change would be backward incompatible with super anti pattern usage, wouldn't it? In such case can we go on speaking about backward incompatible?

I don't understand your questions. I know that it's not ideal to expose a non-final class with static methods as API, but given that this class has been like this for 11 years, I really don't see the urgency to change it now. On top of that, you'd need to bump the `org.apache.sling.api.resource` package version to 3.0.0, which will break a lot of implementations of the `Resource` API.

**Comment by npeltier** [comment]
i thought we could have skipped baseline check for that, but i get your point, will close

**Comment by raducotescu** [comment]
Skipping the baseline check equals to asking for trouble, especially with this package. Sorry! 🙃

**Pull request closed without merging**
