### PR TITLE
SLING-11546: Edited calendar toString method so it explicitly adds th…

### PR DESCRIPTION
**Pull request by JesseOosterwijk**
…e timezone to the string. This fixes the issue of losing timezone information.

Also tested if any of the other converts suffer from the same issue.

### CODE REVIEW

**Review by cziegeler — APPROVED** [review]

**Comment by henrykuijpers** [comment]
@cziegeler  Can this PR be merged safely? :)  We're also running into this issue -- Timezone information is lost when calling this method

**Review by joerghoh — APPROVED** [review]

**Comment by joerghoh** [comment]
@rombert it's probably better to drop the Java17 build for the moment.

**Comment by rombert** [comment]
@joerghoh - this looks like a case of https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=255071690#CommonIssueswhenbuildingwithnewerJDKs(11or17)-TestfailureswhentryingtoinstrumentclasseswithMockito, should not be hard to fix in case anyone wants to give it a shot.

**Comment by joerghoh** [comment]
@rombert https://issues.apache.org/jira/browse/SLING-11965

Just updating the mockito.core is not enough; it fixes these errors though but now I get other failures :-)

**Comment by rombert** [comment]
> > @rombert https://issues.apache.org/jira/browse/SLING-11965
> > Just updating the mockito.core is not enough; it fixes these errors though but now I get other failures :-)
> 
> But it can't hurt, right? #50

Ah, it was https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=255071690#CommonIssueswhenbuildingwithnewerJDKs(11or17)-FailurewithOSGiConverter as well. Java 17 works locally for me, let's see.

**Comment by rombert** [comment]
@JesseOosterwijk The master branch now builds cleanly on Java 17, can you please rebase your changes and push them so we get a meaningful CI check? Thanks!

**Comment by rombert** [comment]
@joerghoh - CI is clean, feel free to merge . @JesseOosterwijk - many thanks for your patience.

**Comment by JesseOosterwijk** [comment]
Hi is there an ETA for this merge? This is still an issue in the project atm.

**Review by cziegeler — APPROVED** [review]

**Pull request merged**
